### ISSUE TITLE
WS assumes local endpoint

### ISSUE THREAD

**Issue by joeha480** [daisy/pipeline-clientlib-java#20] opened 2017-09-11 08:31 UTC
This line (https://github.com/daisy/pipeline-clientlib-java/blob/becd528727957fba9f5a2463d0ab591f1a6e806f/clientlib-java-httpclient/src/main/java/org/daisy/pipeline/client/http/WS.java#L57) throws an error when the endpoint is remote. A localhost endpoint is implicitly required, since the endpoint cannot be set when initializing.

```
[error] failed to parse /alive response
[error] org.daisy.pipeline.client.Pipeline2Exception: Error while GETing.
	at org.daisy.pipeline.client.http.Pipeline2HttpClient.getDelete(Pipeline2HttpClient.java:100)
	at org.daisy.pipeline.client.http.Pipeline2HttpClient.get(Pipeline2HttpClient.java:61)
	at org.daisy.pipeline.client.http.WS.alive(WS.java:100)
	at org.daisy.pipeline.client.http.WS.checkIfLocal(WS.java:656)
	at org.daisy.pipeline.client.http.WS.<init>(WS.java:57)
	at org.daisy.dotify.systemtest.WebServiceTest.setup(WebServiceTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.apache.http.conn.HttpHostConnectException: Connection to http://localhost:8181 refused
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:150)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:575)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:425)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
	at org.daisy.pipeline.client.http.Pipeline2HttpClient.getDelete(Pipeline2HttpClient.java:96)
	... 27 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:123)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:148)
	... 35 more
```

**Comment by bertfrees** [comment] 2017-09-11 13:49
@josteinaj It sounds like we need a WS constructor that accepts an endpoint, or make the `checkIfLocal` lazy. So you volunteered to fix this issue?

**Comment by josteinaj** [comment] 2017-09-12 07:51
@bertfrees I probably won't have time right now to fix it so I probably shouldn't have self-assigned this issue. Feel free to work on it if you want to.

**Comment by bertfrees** [comment] 2017-09-12 11:20
OK I'll have a look.

**Comment by bertfrees** [comment] 2017-09-21 17:01
@joeha480 I have tested this and although there is an error message, which should probably be removed, the WS works fine after you have called the `setEndPoint` method.

**Comment by bertfrees** [comment] 2017-09-25 18:27
Could you confirm this? Or do you get an actual Java exception, or no response when posting your job?

**Comment by joeha480** [comment] 2017-10-11 08:45
@bertfrees we have never successfully submitted any file remotely. I don't know if this error is harmless or not, but we're not getting anything through.

**Comment by josteinaj** [comment] 2017-10-11 09:36
@joeha480 last week while discussing the docker image for pipeline 2, we fixed some things in the http-client regarding remote mode. Have you tried version [2.0.2](https://search.maven.org/#artifactdetails|org.daisy.pipeline|clientlib-java-httpclient|2.0.2|jar)?

**Comment by bertfrees** [comment] 2017-10-11 09:38
OK. Is the problem that you can not post a job, or is the problem that you can not download results?

Jostein recently fixed something in the downloading part: https://github.com/daisy/pipeline-clientlib-java/pull/21.

It's funny though because [the test that I created for this issue](https://github.com/daisy/pipeline/blob/a2087baccd05d2690193b84ae96ffa063660f07d/clientlib-java/clientlib-java-httpclient/src/test/java/WSRemoteTest.java) did not have any problems at all. Maybe we need a better test, e.g. Docker based.

**Comment by bertfrees** [comment] 2017-10-11 10:15
Ideally we should be able to run [your test](https://github.com/mtmse/pipeline-system-tests/blob/master/src/org/daisy/dotify/systemtest/WebServiceTest.java). I'll just try to recreate it using Docker.

**Comment by bertfrees** [comment] 2017-10-11 13:06
After changing my test to use Docker I indeed hit the expected problem that Jostein fixed in #21.
I get a `java.net.ConnectException: Connection refused` when I try to fetch the results. But you're not even getting the results in your test, so there must be another problem...

I've tried to recreate your test, and I'm getting a I/O error:

```
java.lang.RuntimeException: I/O error reported by XML parser processing file:/opt/daisy-pipeline2/data/jobs/1067cc3d-2fa3-446f-a09d-c0fae1eea946/context/DTB23151.xml: /opt/daisy-pipeline2/data/jobs/1067cc3d-2fa3-446f-a09d-c0fae1eea946/context/DTB23151.xml
```

Is that what you were getting too?

You are doing something fishy in your test: https://github.com/mtmse/pipeline-system-tests/blob/7c3d2ec554892bd842ff42e22595a568ae9144e7/src/org/daisy/dotify/systemtest/WebServiceTest.java#L58
```java
js.addContextFile(input, "DTB23151/DTB23151.xml");
```

It should be:
```java
js.addContextFile(input, "DTB23151.xml");
```

But better is to simply drop the line, because your input file will be automatically added to the context on this line down below:
```java
j.getArgument("source").set(input, js);
```

If you do this, the line `js.save(false);` should be moved below the `j.getArgument("source").set(input, js)` line.

Also, this line is redundant:
```java
j.setJobStorage(js);
```

**Comment by bertfrees** [comment] 2017-10-13 18:11
I have pushed some stuff on this branch: https://github.com/daisy/pipeline/compare/docker...clientlib-issue-20. It includes a Docker-based test that you can run and adapt.

1. Check out this branch
2. Run a Pipeline server:
    ```
    docker run -it -e PIPELINE2_WS_HOST=0.0.0.0 -e PIPELINE2_AUTH=false -p 8181:8181 daisyorg/pipeline2
    ```
    If you are on Windows or Mac OS Docker is run inside a VM and you have to configure the VM engine to forward port 8181 otherwise it won't work. For example with VirtualBox: . I'll improve the test later so that this port forwarding isn't needed anymore.

    A problem is that the "daisyorg/pipeline2" image must first be build. On Linux or Mac OSX you can do this with `make dist-docker-image` but on Windows it's slightly more complicated. It's probably better to wait until the image is available on https://hub.docker.com/r/daisyorg. I'll try to take care of that ASAP.
3. Go to the "clientlib-java" subdirectory and run `mvn clean test`

**Comment by bertfrees** [comment] 2017-10-16 14:53
I have done some more changes. These are the new instructions:

1. Check out this branch
2. Go to the "clientlib-java/clientlib-java" subdirectory and run `mvn clean install`
3. Go to the "clientlib-java/clientlib-java-httpclient" subdirectory and run `mvn clean test -Pdocker-test`

**Comment by bertfrees** [comment] 2017-10-19 16:46
@josteinaj I think there are some issues with the clientlib-java API. There are some things that you can do in multiple ways and this causes confusion. See my [comment above](https://github.com/daisy/pipeline-clientlib-java/issues/20#issuecomment-335803055).

One thing I find a bit unclear is that you have a job ID and a job storage ID. Why do you need both? If you don't specify a storage ID the job ID will be taken. Is it even needed to expose the JobStorage to the user?

```
JobStorage js = new JobStorage(job, dir, null);
```

Another example is that you can say this:

```
js.addContextFile(input, "DTB23151/DTB23151.xml");
job.getArgument("source").set(input, js);
```

If you drop the first line, the second will automatically add the file to the context. But like this it doesn't work. I understand that the first line is needed if you want to have two files in different directories reference each other, but I wonder whether the API could handle this a bit better. For example you could require that if you have called the addContextFile function before, you can't use the Argument.set(File) function with that same file, you must use Argument.set(String), or alternatively, get the right path for that file from the storage. (Also it should not be allowed to add the same file to the storage twice with different paths.)

Also why do you need to pass the JobStorage to Argument.set? Shouldn't the argument already have access to that information?

**Comment by josteinaj** [comment] 2017-10-20 07:43
I think the short answer is that I've attempted to keep the job storage stuff a bit separate from the rest of the API, since you may not want to use the job storage functionality.

But yes, we can improve it. I won't have time to work much on this now, but I can review PRs.

**Comment by bertfrees** [comment] 2017-10-20 09:11
When would you not want to use the job storage? Trying to understand.

> but I can review PRs.

Haha. Ok good to know ;)

**Comment by josteinaj** [comment] 2017-10-20 12:29
> When would you not want to use the job storage

Hmm, not sure. But maybe you might want to provide your own implementation of a job storage. If you think it makes sense, we could probably integrate the job storage a bit more.

**Comment by bertfrees** [comment] 2017-10-20 12:38
You can keep supporting that use case by allowing people to subclass Job, but remove JobStorage from the Job API.

**Comment by joeha480** [comment] 2017-10-23 09:26
@bertfrees I found out that files _are_ transferred in our test (to /tmp), however they are not unpacked (at least not in the correct location). Maybe that has something to do with the location of the jobs? `/var/opt/daisy-pipeline2/jobs/`

Is there a way to get some information about the unpacking? I can't seem to find any info on that in the logs.

Interestingly, pipeline seems to think that the file transferred should be at this location `/opt/daisy-pipeline2/` when starting the script.

(I tried your test, but int fails on my Ubuntu machine.)

**Comment by bertfrees** [comment] 2017-10-23 10:35
Sounds like something is wrong with the RPM package, or with your configuration. Maybe you can try with just the ZIP to compare?

We should get the test working. I could then for example create a Dockerfile that installs the RPM which you could then use in the clientlib-java tests. Can you give me some more info about the test failure?

There is no info in the logs about the job resource unzipping at the moment. It happens in framework-core/src/main/java/org/daisy/pipeline/job/impl/IOHelper.java. Also useful I think would be to get the full list of Pipeline configuration properties in the logs. But maybe you can just tell me what is in your system.properties file?

**Comment by bertfrees** [comment] 2017-12-19 16:18
@joeha480 What is the status here? Have you got more info for me about the test failure?

**Comment by rdeltour** [comment] 2018-01-04 10:18
@joeha480 Bert and I were triaging our issues today, and we're wondering what to do with this one. Is it a critical issue for MTM?

If it's a blocking or priority issue on your side, we can put it in the next release milestone, but we'd need some input since Bert wasn't able to reproduce it.

If it's no longer an issue for you, we would postpone the issue or closed a `wontfix`.

Thoughts?

**Comment by joeha480** [comment] 2018-02-06 16:01
@rdeltour I think you can close it.

**Closed** 2018-07-19 13:46 UTC
Labels: 2 - In Progress, accepted, bug
